baseURL = "https://nicks-playground.net/"
languageCode = "en-us"
title = "Nick's Awesome Cloud Blog"
theme = "cayman-hugo-theme"
copyright = "Nick Brandaleone"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[Author] 
  name = "Nick Brandaleone"
  profile = ""

[taxonomies]
  tag = "tags"

[params]
  mainSections = ["posts"]
  intro = true
  project_name = "Above The Cloud"
  project_tagline = "My experiences with AWS and GCP"
  # github = "https://github.com/nbrandaleone"
  # linkedin = "https://www.linkedin.com/in/nbrandaleone/"
  # twitter = "https://twitter.com/nbrandaleone"
  # email = "nbrand@mac.com"
  dateFormat = "Mon, Jan 2, 2006"

[params.social.share]
  facebook = false
  linkedin = true
  twitter = true
  whatsapp = false
  email = true

[permalinks]
  post = "/:year/:month/:title/"

[menu]
[[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
[[menu.nav]]
  name = "Projects"
  url = "/project/"
  weight = 2
[[menu.nav]]
  name = "Helicopters"
  url = "/helicopters/"
  weight = 3
[[menu.nav]]
  name = "About"
  url = "/page/about"
  weight = 4

[sitemap]
changefreq = "monthly"

[deployment.targets]
name = "gcs"
URL = "gs://nicks-playground.net"

